alter tabnet_fit and tabnet_pretrain
mlverse/tabnet pull request #42
Opened 2021-03-24 03:54 UTC by cmcmaster1

Allow model configuration seperate to tabnet_fit, so it can be passed to tabnet_fit via the config variable (as a list).

2021-03-25 22:09 UTC, dfalbel requested changes
Thanks very much @cmcmaster1 ! This looks great!  
I added two comments :)

2021-03-25 22:09 UTC, dfalbel commented on R/model.R
> +                          lambda_sparse = 1e-3,
I think we should avoid renaming parameters at this point because it's likely going to break others code. Can we keep them the same?

2021-03-25 22:09 UTC, dfalbel commented on R/hardhat.R
> +tabnet_fit.data.frame <- function(x, y, tabnet_model = NULL, config = tabnet_config(), ..., from_epoch = NULL) {
Can you add an `@param` tag documenting the new `config` parameter?

2021-03-28 02:21 UTC, cmcmaster1 commented on R/hardhat.R
> +tabnet_fit.data.frame <- function(x, y, tabnet_model = NULL, config = tabnet_config(), ..., from_epoch = NULL) {
Done.

2021-03-28 02:22 UTC, cmcmaster1 commented on R/model.R
> +                          lambda_sparse = 1e-3,
Kept the names by renaming within the `tabnet_fit` and `tabnet_pretrain` functions.

2021-04-01 14:14 UTC, dfalbel commented
Looks great! Thanks very much @cmcmaster1

2021-04-01 14:14 UTC, merged